name: "Chore"
description: Maintenance task, dependency update, or cleanup
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        > **Note:** Do not manually add labels or select an issue type. Automation will handle this.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description
      placeholder: "Update dependencies"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which area does this affect?
      options:
        - Admin
        - API
        - DevOps
        - Quant
        - Smart Contracts
        - UI
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - Medium
        - Low
        - High
        - Critical
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Initial status (defaults to Backlog if not selected)
      options:
        - Backlog
        - Icebox
        - In Progress
        - Blocked
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > **BE AWARE:** Please allow automation to complete (~2mins) before editing ticket again to avoid issues.
