name: "Feature: UI"
description: Request a new UI feature or component
labels: ["feature", "ui"]
body:
  - type: markdown
    attributes:
      value: |
        > **Note:** Do not manually add labels or select an issue type. Automation will handle this.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description
      placeholder: "Add dark mode toggle"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this feature do?
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: Design / Mockup
      description: Attach screenshot, Figma link, or describe the expected UI
      placeholder: "Attach image or paste link"
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Component renders correctly
        - [ ] Responsive on mobile
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > **BE AWARE:** Please allow automation to complete (~2mins) before editing ticket again to avoid issues.
